<html>
<head>
    <title>xero-php Sample App</title>

    <base href="/">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col">
            <h2>xero-php Sample App</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a href="oauth/request-token"><img src="assets/images/connect_xero_button_blue.png"></a>
        </div>
    </div>
</div>
</body>
</html>