<html>
<head>
    <title>XeroPHP Sample Application – <?= $this->e($title) ?></title>

    <base href="/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="assets/css/style.css">

</head>
<body>


<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <span class="navbar-brand">XeroPHP Sample Application</span>
        <?php if (isset($organisation_name)): ?>
            <span class="navbar-text">Connected to <?= $this->e($organisation_name) ?> &middot;
                <a href="/application/disconnect">Disconnect</a></span>
        <?php endif; ?>
    </div>
</nav>

<br/>


<div class="container">

    <div class="content">
        <?= $this->section('content') ?>
    </div>

</div>
</body>
</html>