<?php $this->layout('base', ['title' => 'Connect']) ?>

<div class="d-flex justify-content-center" style="position: relative; top: 100px;">
    <div class="card col-md-5">
        <div class="card-body">
            <h5 class="card-title">Connect to Xero</h5>
            <p class="card-text">To continue, connect an organisation with your application.</p>
            <form method="post">
                <input type="image" src="assets/images/connect_xero_button_blue.png" alt="Connect to Xero"/>
            </form>
        </div>
    </div>
</div>