<?php $this->layout('base', ['title' => 'Endpoints', 'organisation_name' => $organisation_name]) ?>

<div id="endpoints-accordion" class="col-md-3">
    <?php $this->insert('partials/accordion-item', ['key' => 'accounts', 'name' => 'Accounts', 'endpoints' => [
        'create' => 'Get',
        'read' => 'Create',
        'update' => 'Update',
        'delete' => 'Delete',
        'archive' => 'Archive',
        'add-attachment' => 'Add Attachment',
    ]]) ?>

</div>