<?php $this->layout('base', ['title' => 'Endpoints', 'organisation_name' => $organisation_name]) ?>

<div class="row">

    <div class="endpoints col-md-3">
        <h5>Endpoints</h5>
        <div id="endpoints-accordion">

            <?php
            $c = ['create' => 'Create'];
            $r = ['get' => 'Get'];
            $u = ['update' => 'Update'];
            $d = ['delete' => 'Delete'];
            $archive = ['archive' => 'Archive'];
            $attachment = ['add-attachment' => 'Add Attachment'];
            $crud = $c + $r + $u + $d;

            $this->insert('partials/accordion-item', [
                'open' => true,
                'key' => 'items',
                'name' => 'Items',
                'endpoints' => $crud
            ]);

            $this->insert('partials/accordion-item', [
                'key' => 'invoices',
                'name' => 'Invoices',
                'endpoints' => $c + $r + $d
            ]);

            /*$this->insert('partials/accordion-item', [
                'key' => 'bank-transfers',
                'name' => 'Bank Transfers',
                'endpoints' => $c + $r + $attachment
            ]);

            $this->insert('partials/accordion-item', [
                'key' => 'branding-themes',
                'name' => 'Branding Themes',
                'endpoints' => $r
            ]);

            $this->insert('partials/accordion-item', [
                'key' => 'contacts',
                'name' => 'Contacts',
                'endpoints' => $c + $r + $u + $archive + $attachment
            ]);

            $this->insert('partials/accordion-item', [
                'key' => 'contact-groups',
                'name' => 'Contact Groups',
                'endpoints' => $c + $r + $u + $d + ['add-contact' => 'Add Contact', 'remove-contact' => 'Remove Contact']
            ]);*/

            ?>

        </div>
    </div>

    <div class="col-md-9">
        <h5>Request</h5>

        <div class="align-items-center endpoint-control">
            <span class="badge badge-primary object"></span>
            <span class="divider">/</span>
            <span class="badge badge-primary method"></span>
            <span class="divider">/</span>

            <input id="guid-input" type="text" title="Enter a GUID" maxlength="36"/>
            <a href="#" class="badge badge-light" id="add-guid" style="text-transform: inherit">+ Add GUID</a>

            <div class="ml-auto">
                <button class="btn btn-primary btn-sm" id="run-endpoint">Make Request</button>
            </div>
        </div>

        <hr>

        <div class="card">
            <div class="card-header">Code</div>
            <div class="card-body">
                <pre class="function-location text-info"></pre>
                <pre><code class="function-body php">no requests have been made</code></pre>
            </div>
        </div>

        <br>

        <div class="card">
            <div class="card-header">Response</div>
            <div class="card-body danger">
                <pre><code class="payload-response">no requests have been made</code></pre>
            </div>
        </div>

    </div>

</div>

<script type="application/javascript">

    $(function () {

        var $function_location = $('.function-location');
        var $function_body = $('.function-body');
        var $payload_response = $('.payload-response');
        var $endpoint = $('.endpoint-control');
        var $guid = $('#guid-input');
        var $run_button = $('#run-endpoint');

        var $add_guid = $('#add-guid').click(function (e) {
            e.preventDefault();
            $add_guid.hide();
            $guid.show();
        });

        $('#endpoints-accordion').on('click', 'a.method', function (e) {
            e.preventDefault();

            $add_guid.show();
            $guid.val('').hide();

            $endpoint.find('.object').html(this.getAttribute('data-object-name'));
            $endpoint.find('.method').html(this.getAttribute('data-method-name'))
                .get(0).className = this.className; //Copy styles over

            //Show controls
            if (!$endpoint.hasClass('d-flex')) {
                $endpoint.addClass('d-flex');
            }

            $run_button.attr('data-endpoint', '/' + this.getAttribute('data-object-key') + '/' + this.getAttribute('data-method-key'));

        });


        $run_button.click(function (e) {
            e.preventDefault();
            //These are all POST so browsers don't do any funny caching
            var endpoint = this.getAttribute('data-endpoint');

            //If a GUID has been supplied, add it to the url
            if ($guid.val()) {
                endpoint += '/' + $guid.val();
            }

            $run_button.attr('disabled', true);

            $.ajax(endpoint, {headers: {Accept: "application/json"}, method: 'post'})
                .done(function (data) {
                    $function_location.html(data.function_location);
                    $function_body.html(hljs.highlightAuto(data.function_body).value);
                    $payload_response.html(hljs.highlightAuto(data.payload_response).value);

                    $payload_response.parents('.card').addClass('border-success').removeClass('border-danger');
                    $run_button.attr('disabled', false);
                })
                .fail(function (error) {
                    if (error.responseJSON.status_code === 401) {
                        alert('Session expired');
                    }

                    $payload_response.html(error.responseJSON.message);
                    $payload_response.parents('.card').removeClass('border-success').addClass('border-danger');
                    $run_button.attr('disabled', false);
                });
        });


    });

</script>