<div class="card">
    <div class="card-header">
        <button class="btn btn-link"
                data-toggle="collapse"
                data-target="#collapse-<?= $key ?>"
                aria-controls="collapse-<?= $key ?>"
                aria-expanded="true">
            <?= $this->e($name) ?>
        </button>
    </div>

    <?php $map=['create' => 'primary', 'get' => 'success', 'update' => 'warning', 'delete' => 'danger']; ?>

    <div id="collapse-<?= $key ?>" class="object collapse<?= $open ? ' show' : '' ?>" data-parent="#endpoints-accordion">
        <div class="card-body">
            <?php foreach ($endpoints as $endpoint_key => $endpoint_name): ?>
                <div>
                    <a class="method badge badge-<?= $map[$endpoint_key] ?: 'secondary' ?>" href="#"
                       data-object-key="<?= $key ?>"
                       data-object-name="<?= $name ?>"
                       data-method-key="<?= $endpoint_key ?>"
                       data-method-name="<?= $endpoint_name ?>"><?= $endpoint_name ?></a>
                </div>
            <? endforeach; ?>
        </div>
    </div>
</div>